import 'factory_helpers.dart';

sealed class ItemOrdemServicoModelFactory {
  static ItemOrdemServicoModel make({
    String? id,
    String? ordemServicoId,
    String? criadoPorId,
    String? atualizadoPorId,
    String? descricao,
    CategoriaItemModel? categoria,
    MaterialItemModel? material,
    int? quantidade,
    String? larguraCm,
    String? alturaCm,
    String? profundidadeCm,
    String? areaM2,
    String? valorDeclarado,
    String? estadoAtual,
    String? cuidadosEspeciais,
    String? valorUnitarioBase,
    String? valorUnitarioDesconto,
    String? valorUnitarioFinal,
    String? valorTotalBruto,
    String? valorTotalDesconto,
    String? valorTotalFinal,
    String? chaveFotoInicial,
    String? urlFotoInicial,
    bool? ativo,
    DateTime? dataCriacao,
    DateTime? dataAtualizacao,
    DateTime? dataExclusao,
    OrdemServicoModel? ordemServico,
    UsuarioModel? criadoPor,
    UsuarioModel? atualizadoPor,
    List<ServicoExecutadoItemModel>? servicosExecutados,
    List<ObservacaoModel>? observacoes,
    List<IntencaoUploadModel>? intencoesUpload,
  }) {
    final model = ItemOrdemServicoModel(
      id: id ?? makeFakeId(),
      ordemServicoId: ordemServicoId ?? makeFakeId(),
      criadoPorId: criadoPorId ?? makeFakeId(),
      atualizadoPorId: atualizadoPorId ?? makeFakeId(),
      descricao: descricao ?? faker.lorem.sentence(),
      categoria: categoria ?? makeFakeEnum(CategoriaItemModel.values),
      material: material ?? makeFakeEnum(MaterialItemModel.values),
      quantidade: quantidade ?? faker.randomGenerator.integer(10, min: 1),
      larguraCm: larguraCm ?? makeFakeDecimalString(),
      alturaCm: alturaCm ?? makeFakeDecimalString(),
      profundidadeCm: profundidadeCm ?? makeFakeDecimalString(),
      areaM2: areaM2 ?? makeFakeDecimalString(),
      valorDeclarado: valorDeclarado ?? makeFakeMoney(),
      estadoAtual: estadoAtual ?? faker.lorem.sentence(),
      cuidadosEspeciais: cuidadosEspeciais ?? faker.lorem.sentence(),
      valorUnitarioBase: valorUnitarioBase ?? makeFakeMoney(),
      valorUnitarioDesconto: valorUnitarioDesconto ?? makeFakeMoney(),
      valorUnitarioFinal: valorUnitarioFinal ?? makeFakeMoney(),
      valorTotalBruto: valorTotalBruto ?? makeFakeMoney(),
      valorTotalDesconto: valorTotalDesconto ?? makeFakeMoney(),
      valorTotalFinal: valorTotalFinal ?? makeFakeMoney(),
      chaveFotoInicial: chaveFotoInicial ?? makeFakeStorageKey(),
      urlFotoInicial: urlFotoInicial ?? faker.internet.httpsUrl(),
      ativo: ativo ?? true,
      dataCriacao: dataCriacao ?? makeFakeDateTime(),
      dataAtualizacao: dataAtualizacao ?? makeFakeDateTime(),
      dataExclusao: dataExclusao,
      ordemServico: ordemServico,
      criadoPor: criadoPor,
      atualizadoPor: atualizadoPor,
      servicosExecutados: servicosExecutados,
      observacoes: observacoes,
      intencoesUpload: intencoesUpload,
    );

    return model;
  }
}
