import 'factory_helpers.dart';

sealed class OrdemServicoModelFactory {
  static OrdemServicoModel make({
    String? id,
    String? codigo,
    String? clienteId,
    String? criadoPorId,
    String? atualizadoPorId,
    String? responsavelId,
    String? aprovadoPorDescontoId,
    StatusOrdemServicoModel? status,
    CanalEntradaOrdemServicoModel? canalEntrada,
    DateTime? agendadaColetaEm,
    DateTime? agendadaEntregaEm,
    DateTime? iniciadaEm,
    DateTime? finalizadaEm,
    DateTime? canceladaEm,
    Map<String, dynamic>? snapshotEnderecoColeta,
    Map<String, dynamic>? snapshotEnderecoEntrega,
    Map<String, dynamic>? snapshotCliente,
    Map<String, dynamic>? snapshotPoliticaDesconto,
    String? percentualDesconto,
    String? valorDesconto,
    String? valorFrete,
    String? valorSubtotal,
    String? valorTotal,
    String? motivoDesconto,
    String? observacoesInternas,
    String? observacoesCliente,
    String? chaveAssinaturaCliente,
    String? urlAssinaturaCliente,
    DateTime? assinadaEm,
    String? chavePdf,
    String? urlPdf,
    bool? ativo,
    DateTime? dataCriacao,
    DateTime? dataAtualizacao,
    DateTime? dataExclusao,
    ClienteModel? cliente,
    UsuarioModel? criadoPor,
    UsuarioModel? atualizadoPor,
    UsuarioModel? responsavel,
    UsuarioModel? aprovadoPorDesconto,
    List<ItemOrdemServicoModel>? itens,
    List<HistoricoStatusOrdemServicoModel>? historicoStatus,
    List<ObservacaoModel>? observacoes,
    List<ImagemOrdemServicoModel>? imagens,
    FaturaModel? fatura,
    List<IntencaoUploadModel>? intencoesUpload,
  }) {
    final model = OrdemServicoModel(
      id: id ?? makeFakeId(),
      codigo: codigo ?? makeFakeCode(prefix: 'OS'),
      clienteId: clienteId ?? makeFakeId(),
      criadoPorId: criadoPorId ?? makeFakeId(),
      atualizadoPorId: atualizadoPorId ?? makeFakeId(),
      responsavelId: responsavelId ?? makeFakeId(),
      aprovadoPorDescontoId: aprovadoPorDescontoId ?? makeFakeId(),
      status: status ?? makeFakeEnum(StatusOrdemServicoModel.values),
      canalEntrada:
          canalEntrada ?? makeFakeEnum(CanalEntradaOrdemServicoModel.values),
      agendadaColetaEm: agendadaColetaEm ?? makeFakeDateTime(),
      agendadaEntregaEm: agendadaEntregaEm ?? makeFakeDateTime(),
      iniciadaEm: iniciadaEm ?? makeFakeDateTime(),
      finalizadaEm: finalizadaEm ?? makeFakeDateTime(),
      canceladaEm: canceladaEm,
      snapshotEnderecoColeta: snapshotEnderecoColeta ??
          makeFakeMap(label: 'snapshotEnderecoColeta'),
      snapshotEnderecoEntrega: snapshotEnderecoEntrega ??
          makeFakeMap(label: 'snapshotEnderecoEntrega'),
      snapshotCliente: snapshotCliente ?? makeFakeMap(label: 'snapshotCliente'),
      snapshotPoliticaDesconto: snapshotPoliticaDesconto ??
          makeFakeMap(label: 'snapshotPoliticaDesconto'),
      percentualDesconto: percentualDesconto ?? makeFakePercentage(),
      valorDesconto: valorDesconto ?? makeFakeMoney(),
      valorFrete: valorFrete ?? makeFakeMoney(),
      valorSubtotal: valorSubtotal ?? makeFakeMoney(),
      valorTotal: valorTotal ?? makeFakeMoney(),
      motivoDesconto: motivoDesconto ?? faker.lorem.sentence(),
      observacoesInternas: observacoesInternas ?? faker.lorem.sentence(),
      observacoesCliente: observacoesCliente ?? faker.lorem.sentence(),
      chaveAssinaturaCliente: chaveAssinaturaCliente ?? makeFakeStorageKey(),
      urlAssinaturaCliente: urlAssinaturaCliente ?? faker.internet.httpsUrl(),
      assinadaEm: assinadaEm ?? makeFakeDateTime(),
      chavePdf: chavePdf ?? makeFakeStorageKey(),
      urlPdf: urlPdf ?? faker.internet.httpsUrl(),
      ativo: ativo ?? true,
      dataCriacao: dataCriacao ?? makeFakeDateTime(),
      dataAtualizacao: dataAtualizacao ?? makeFakeDateTime(),
      dataExclusao: dataExclusao,
      cliente: cliente,
      criadoPor: criadoPor,
      atualizadoPor: atualizadoPor,
      responsavel: responsavel,
      aprovadoPorDesconto: aprovadoPorDesconto,
      itens: itens,
      historicoStatus: historicoStatus,
      observacoes: observacoes,
      imagens: imagens,
      fatura: fatura,
      intencoesUpload: intencoesUpload,
    );

    return model;
  }
}
